[toolchain]
anchor_version = "0.29.0"

[features]
seeds = true
skip-lint = false

[programs.mainnet]
merkle_distributor = "4T5uFmTdHR9wC5x9vW9ywpqK4MhDMmPtaV2mzHBANGhM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://mainnet.helius-rpc.com/?api-key=40963904-fc44-47f3-bed3-f01a0047f70a"
wallet = "/Users/mykyta/.config/solana/id.json"

[workspace]
members = ["programs/merkle-distributor"]

[scripts]
test = "yarn mocha"
